### ISSUE TITLE
Add selection mechanism for different JVS IOs

### ISSUE THREAD

**Issue by RedOne87** [bobbydilley/OpenJVS3#10]
Add selection mechanism for different JVS IOs  (see initIO()).
This could be a config file, command argument..

**Comment by GXTX** [comment]
Are there any known games which check for specific ID name? If not then I don't think this is worth spending time on.

**Comment by bobbydilley** [comment]
This has been discussed privately, and I'll copy in the reasons from RedOne87 below.
For general information purposes, some Namco games such as Ninja Assault do check the specific JVS IO name - all others (as far as i'm aware) do not.

-- Reasons from RedOne87 to use different IOs --

The different IO boards could actually be necessary when I comes to analog values. The number of bit of the analog values are definied in the CMD_CAPABILITIES command and I dont know what a naomi game will do if it suddenly gets 14bits but at the time of programming there was no IO with 14bits. Most likely the implementation will just look at the higher bits and mask out the others.. but you never know :) . Also when using only 8 bits a at lindbergh system you will lose a lot of precision due to the worse quantisation... it tested it when I fixed the analog scaling stuff in OpenJVS1 and the loss of precision was noticealbe.
When I bought my LB stuff i also bought like 4 IO board (Type 3 Sega 837-14572 and Type 1?) for there are some games that are not working with the other one.. I don't recall the details out of the head..

So I think I'd prefere having different types of emulated IO boards because of the precision thing for my lb and naomi. I do not mind if currently we hard-code / use a define to use a default one or if you add a generic "OpenJVS IO" and we can see later if there is a need to switch it during runtime or for specific games the structure is there to have a flexible approach..
